# Generated by Django 4.2.1 on 2023-07-12 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dirección', models.CharField(default='', max_length=50)),
                ('correo', models.CharField(default='', max_length=50)),
                ('teléfono', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cotización',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
                ('fechaSolicitud', models.DateField()),
                ('peso', models.PositiveIntegerField()),
                ('dimensiones', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaInicio', models.DateField()),
                ('lugarOrigen', models.CharField(max_length=50)),
                ('lugarDestino', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='Transporteapp.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Vehículo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=2023)),
                ('patente', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numeroSeguimiento', models.PositiveIntegerField(blank=True, unique=True)),
                ('comentario', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('En evaluación', 'En evaluación'), ('Despachado', 'Despachado'), ('En traslado', 'En Traslado'), ('Interrumpido', 'Interrumpido'), ('Cancelado', 'Cancelado'), ('Cumplido', 'Cumplido')], default='', max_length=50)),
                ('valor', models.FloatField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transporteapp.cotización')),
                ('transportista', models.ManyToManyField(blank=True, related_name='Transportistas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Transporteapp.vehículo')),
            ],
            options={
                'verbose_name_plural': 'Orden de servicio',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='bitacora_imagenes/')),
                ('imagen2', models.ImageField(blank=True, upload_to='bitacora_imagenes/')),
                ('imagen3', models.ImageField(blank=True, upload_to='bitacora_imagenes/')),
                ('Orden_de_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Transporteapp.ordendeservicio')),
            ],
        ),
    ]
