# Generated by Django 4.2.1 on 2023-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transporteapp', '0002_remove_bitacora_orden_de_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dirección',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='teléfono',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cotización',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='estado',
            field=models.CharField(choices=[('En evaluación', 'En evaluación'), ('Despachado', 'Despachado'), ('En traslado', 'En Traslado'), ('Interrumpido', 'Interrumpido'), ('Cancelado', 'Cancelado'), ('Cumplido', 'Cumplido')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordendeservicio',
            name='numeroSeguimiento',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
